apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
data:
  RabbitMq__Host: rabbitmq
  RabbitMq__Username: guest
  RabbitMq__PaymentProcessedQueue: catalog-payment-processed
  Jwt__Issuer: UsersAPI
  Jwt__Audience: FCG
  Sqs__Region: us-east-1
  Sqs__NotificationsQueueUrl: https://sqs.us-east-1.amazonaws.com/174302433776/fcg-notifications-queue
  ConnectionStrings__Redis: redis:6379
  ConnectionStrings__MongoDB: mongodb://mongo:27017
  Mongo__Database: fcg_catalog
