apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secrets
type: Opaque
stringData:
  RabbitMq__Password: guest
  CatalogConnectionString: Server=sqlserver,1433;Database=FCGCatalogDb;User Id=sa;Password=ArquiteturaFiap.NET@2026;TrustServerCertificate=True;
